apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # scale up for dev
  template:
    spec:
      containers:
        - name: backend
          image: siddhartha54/water-quality-monitoring-backend:latest # override image
          env:
            - name: ENVIRONMENT
              value: "dev"
