# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  # The password is read from values.yaml and then base64 encoded by Helm.
  password: {{ .Values.mysql.password | b64enc | quote }}