apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: siddhartha54/water-quality-monitoring-frontend:latest
          ports:
            - containerPort: 80
          env: 
            - name: REACT_APP_API_URL
              value: "http://backend:8000/api"   # Backend Service URL inside cluster
