# water-quality-monitoring/Chart.yaml

apiVersion: v2
name: water-quality-monitoring
version: 0.1.0
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: mysql
    version: "9.10.6" # Use a stable, known version
    repository: "https://charts.bitnami.com/bitnami"
    alias: mysql