apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret # The name our patch will reference
type: Opaque
data:
  # The key is 'password', and the value is the base64 encoded string
  # 'echo -n "your-dev-password" | base64'
  password: bXlzcWwtcm9vdC1wYXNz # This decodes to 'mysql-root-pass'