# helm-chart/charts/backend/templates/service-alias.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend # This name MUST be "backend" to match what Nginx is looking for
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 6 }}