name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      # This permission is required to push a commit back to the repository
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch all history for all tags and branches, required for pushing
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Image Tag
      id: tag_generator # Using a clearer ID
      run: |
        # Generate a random 2-digit number for the tag
        TAG=$(( RANDOM % 90 + 10 ))
        echo "Generated tag: $TAG"
        # Set the tag as a step output to be used by other steps
        echo "TAG=$TAG" >> $GITHUB_OUTPUT

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: siddhartha54/water-quality-monitoring-frontend:${{ steps.tag_generator.outputs.TAG }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        # Corrected the backend image name to match the values.yml file
        tags: siddhartha54/water-quality-monitoring-backend:${{ steps.tag_generator.outputs.TAG }}

    - name: Update Kubernetes Deployment YAML
      run: |
        # Use the correct file extension '.yml' as per your file name
        # Use a more robust sed command that finds the repository line, then modifies the tag on the NEXT line
        sed -i -E '/repository: siddhartha54\/water-quality-monitoring-frontend/!b;n;s/tag: .*/tag: "${{ steps.tag_generator.outputs.TAG }}"/' helm-chart/values-prod.yaml
        sed -i -E '/repository: siddhartha54\/water-quality-monitoring-backend/!b;n;s/tag: .*/tag: "${{ steps.tag_generator.outputs.TAG }}"/' helm-chart/values-prod.yaml
        
        echo "Updated helm-chart/values-prod.ymal with tag: ${{ steps.tag_generator.outputs.TAG }}"
        # Print the file contents to the log for verification
        cat helm-chart/values-prod.yaml

    - name: Commit and Push updated deployment YAML
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Use the correct file name and add it only once
        git add helm-chart/values-prod.yaml

        # Commit and push only if there are actual changes to the file
        if ! git diff-index --quiet HEAD; then
          git commit -m "Deploy: Update image tags to ${{ steps.tag_generator.outputs.TAG }}"
          git push
        else
          echo "No deployment changes to commit."
        fi
