name: Notify After Deploy

on:
  workflow_run:
    workflows: ["Build, Push and Deploy"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Email Notification
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587 
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: Bakery App Deployed
        to:  ${{ secrets.EMAIL_TO}}
        from: Bakery CI/CD <${{ secrets.EMAIL_USER }}>
        body: |
          ✅ The latest build has been successfully deployed.
          🕒 Timestamp: ${{ github.event.head_commit.timestamp }}