name: Notify After Deploy

on:
  workflow_run:
    workflows: ["Build, Push and Deploy"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}       # Gmail email address (e.g. your.email@gmail.com)
          password: ${{ secrets.EMAIL_PASS }}       # Gmail App Password (NOT your Gmail login password)
          subject: Water quality monitor App Deployed
          to: ${{ secrets.EMAIL_TO }}                # Recipient email address
          from: Bakery CI/CD <${{ secrets.EMAIL_USER }}>
          body: |
            ✅ The latest build has been successfully deployed.
            🕒 Timestamp: ${{ github.event.workflow_run.updated_at }}
